Update Flux desktop environment and application scripts
- updated `fbdesktop` script to create .desktop files for various applications in the Flux desktop environment.
- updated `fbliveapp` script to manage application installation and execution, including VLC, Firefox ESR, and MiniOS tools.
- updated `fblogout` script for handling logout, restart, and shutdown commands with a graphical interface.
- Included necessary icons for logout, restart, and shutdown actions.
- Updated Thunar to use a locale configuration wrapper for better language support.
- Enhanced package installation scripts across various modules to ensure proper error handling and user feedback.
- Replaced `connman-gtk` with `network-manager-gnome` in package lists for improved network management.
- Updated XML configuration files for XFCE settings, including keyboard layout and desktop appearance.
- Ensured all scripts and configurations are properly structured for the new Flux desktop environment.

diff --git a/linux-live/scripts/04-xfce-desktop/install b/linux-live/scripts/04-xfce-desktop/install
--- a/linux-live/scripts/04-xfce-desktop/install
+++ b/linux-live/scripts/04-xfce-desktop/install
@@ -10,41 +10,23 @@ set -u          # treat unset variable as error
 SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
 
 /condinaut -l "${SCRIPT_DIR}/packages.list" -c "${SCRIPT_DIR}/minios_build.conf" -m "${SCRIPT_DIR}/condinaut.conf"
+if [ $? -ne 0 ]; then
+    echo "Failed to install packages."
+    exit 1
+fi
 
 echo "export QT_QPA_PLATFORMTHEME=gtk2" >>/etc/environment
 
-if [ "$LOCALE" != "en_US" ] && [ "$LOCALE" != "C" ]; then
-    cat <<EOF >/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/keyboard-layout.xml
-<?xml version="1.0" encoding="UTF-8"?>
-
-<channel name="keyboard-layout" version="1.0">
-  <property name="Default" type="empty">
-    <property name="XkbDisable" type="bool" value="false"/>
-    <property name="XkbLayout" type="string" value="us,$LAYOUTID"/>
-    <property name="XkbVariant" type="string" value=","/>
-    <property name="XkbOptions" type="empty">
-      <property name="Group" type="string" value="grp:alt_shift_toggle"/>
-    </property>
-  </property>
-</channel>
-
-EOF
+if [ "$LOCALE" = "en_US" ] || [ "$LOCALE" = "C" ]; then
+    xmlstarlet ed -L \
+        -u '/channel/property/property[@name="XkbOptions"]/property[@name="XkbLayout"]/@value' \
+        -v "us" \
+        "/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/keyboard-layout.xml"
 else
-    cat <<EOF >/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/keyboard-layout.xml
-<?xml version="1.0" encoding="UTF-8"?>
-
-<channel name="keyboard-layout" version="1.0">
-  <property name="Default" type="empty">
-    <property name="XkbDisable" type="bool" value="false"/>
-    <property name="XkbLayout" type="string" value="us"/>
-    <property name="XkbVariant" type="string" value=","/>
-    <property name="XkbOptions" type="empty">
-      <property name="Group" type="string" value="grp:alt_shift_toggle"/>
-    </property>
-  </property>
-</channel>
-
-EOF
+    xmlstarlet ed -L \
+        -u '/channel/property/property[@name="XkbOptions"]/property[@name="XkbLayout"]/@value' \
+        -v "us,$LAYOUTID" \
+        "/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/keyboard-layout.xml"
 fi
 
 echo "nodm nodm/enabled boolean true" | debconf-set-selections
@@ -64,43 +46,7 @@ if [ -f "/usr/share/applications/xfce4-clipman-settings.desktop" ]; then
 fi
 
 mv /usr/bin/thunar /usr/bin/thunar-bin
-cat <<'EOF' >/usr/bin/thunar
-#!/bin/bash
-# Thunar Locale Configuration Wrapper
-# This script checks the system's locale and applies a localized
-# Thunar configuration file if available. It then executes the
-# original Thunar binary.
-# Author: crims0n <https://minios.dev>
-
-if [ "$(echo $LANG | cut -d'_' -f1)" = "pt_BR" ]; then
-    LOCALE="br" # Special case for Brazilian Portuguese
-elif [ "$(echo $LANG | cut -d'_' -f1)" = "C" ]; then
-    LOCALE="en"
-else
-    LOCALE=$(echo $LANG | cut -d'_' -f1)
-fi
-
-SOURCE_FILE=~/.config/Thunar/uca.$LOCALE.xml
-TARGET_FILE=~/.config/Thunar/uca.xml
-
-if [ -f "$SOURCE_FILE" ]; then
-    if [ ! -f "$TARGET_FILE" ] || ! cmp -s "$SOURCE_FILE" "$TARGET_FILE"; then
-        cp "$SOURCE_FILE" "$TARGET_FILE"
-    fi
-fi
-
-# Check if the system supports aufs
-if ! grep -q aufs /proc/filesystems; then
-    # Remove specific actions using xmlstarlet
-    if command -v xmlstarlet > /dev/null 2>&1; then
-        xmlstarlet ed -d '//action[icon="module-connect"]' "$TARGET_FILE" > "$TARGET_FILE.tmp"
-        xmlstarlet ed -d '//action[icon="module-disconnect"]' "$TARGET_FILE.tmp" > "$TARGET_FILE"
-        rm "$TARGET_FILE.tmp"
-    fi
-fi
-
-exec /usr/bin/thunar-bin "$@"
-EOF
+mv /usr/bin/thunar.sh /usr/bin/thunar
 chmod +x /usr/bin/thunar
 
 if [ -f /usr/bin/connman-gtk ]; then
@@ -137,11 +83,37 @@ EOF
     rm /usr/share/applications/connman-gtk.desktop
 fi
 
-sed -i 's,<property name="FontName" type="empty"/>,<property name="FontName" type="string" value="Inter 10"/>,g' /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
-sed -i 's,<property name="MonospaceFontName" type="empty"/>,<property name="MonospaceFontName" type="string" value="JetBrains Mono 10"/>,g' /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
-sed -i 's,<property name="Antialias" type="empty"/>,<property name="Antialias" type="int" value="1"/>,g' /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
-sed -i 's,<property name="HintStyle" type="string" value="hintmedium"/>,<property name="HintStyle" type="string" value="hintfull"/>,g' /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
-sed -i 's,Sans Bold 10,Inter Bold 10,g' /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
+# Apply XML changes
+XML_XSETTINGS=/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
+XML_XFWM4  =/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
+
+# Set FontName to "Inter 10"
+xmlstarlet ed -L \
+    -u "//property[@name='FontName']/@type" -v "string" \
+    -i "//property[@name='FontName']"    -t attr -n "value" -v "Inter 10" \
+    "$XML_XSETTINGS"
+
+# Set MonospaceFontName to "JetBrains Mono 10"
+xmlstarlet ed -L \
+    -u "//property[@name='MonospaceFontName']/@type" -v "string" \
+    -i "//property[@name='MonospaceFontName']"    -t attr -n "value" -v "JetBrains Mono 10" \
+    "$XML_XSETTINGS"
+
+# Enable antialiasing
+xmlstarlet ed -L \
+    -u "//property[@name='Antialias']/@type" -v "int" \
+    -i "//property[@name='Antialias']"    -t attr -n "value" -v "1" \
+    "$XML_XSETTINGS"
+
+# Change hint style to "hintfull"
+xmlstarlet ed -L \
+    -u "//property[@name='HintStyle']/@value" -v "hintfull" \
+    "$XML_XSETTINGS"
+
+# Replace "Sans Bold 10" with "Inter Bold 10" in xfwm4.xml
+xmlstarlet ed -L \
+    -u "//property[contains(@value,'Sans Bold 10')]/@value" -v "Inter Bold 10" \
+    "$XML_XFWM4"
 
 if pkg_is_installed "xfce4-terminal"; then
     update-alternatives --set x-terminal-emulator /usr/bin/xfce4-terminal.wrapper >/dev/null 2>&1
@@ -530,7 +502,10 @@ fi
 sed -i -e "/FontName=/s/=.*/=JetBrains Mono Light 10/" /etc/skel/.config/xfce4/terminal/terminalrc
 
 if pkg_is_installed "xfce4-power-manager-plugins"; then
-    sed -i "s/battery/power-manager-plugin/g" /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
+    xmlstarlet ed -L \
+        -u '//property[@type="string"][@value="battery"]/@value' \
+        -v 'power-manager-plugin' \
+        /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
 fi
 
 if pkg_is_installed "xfce4-terminal"; then
@@ -573,13 +548,13 @@ find /usr/share/backgrounds/ -maxdepth 1 -type f ! -name "MiniOS5*" -delete
 
 set_wallpaper() {
     local WALLPAPER=$1
-    local WALLPAPER_FILE="../MiniOS5-wallpaper-$WALLPAPER.jpg"
 
-    # Check if the wallpaper file exists before creating symlinks
-    ln -sf "$WALLPAPER_FILE" /usr/share/backgrounds/xfce/xfce-verticals.png
-    ln -sf "$WALLPAPER_FILE" /usr/share/backgrounds/xfce/xfce-verticals.svg
-    ln -sf "$WALLPAPER_FILE" /usr/share/backgrounds/xfce/xfce-teal.jpg
-    ln -sf "$WALLPAPER_FILE" /usr/share/backgrounds/xfce/xfce-shapes.svg
+    # Update desktop XML to reference selected wallpaper directly
+    local XML_FILE="/etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
+    xmlstarlet ed -L \
+        -u "//property[@name='image-path']/@value" \
+        -v "/usr/share/backgrounds/MiniOS5-wallpaper-${WALLPAPER}.jpg" \
+        "$XML_FILE"
 
     # Remove other wallpaper files
     for OTHER_WALLPAPER in Minimum Flux Standard Toolbox Ultra; do
diff --git a/linux-live/scripts/05-lxqt-apps/install b/linux-live/scripts/05-lxqt-apps/install
--- a/linux-live/scripts/05-lxqt-apps/install
+++ b/linux-live/scripts/05-lxqt-apps/install
@@ -10,8 +10,16 @@ set -u          # treat unset variable as error
 SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
 
 /condinaut -l "$SCRIPT_DIR/$PACKAGE_VARIANT.list" -c "${SCRIPT_DIR}/minios_build.conf" -m "${SCRIPT_DIR}/condinaut.conf"
+if [ $? -ne 0 ]; then
+    echo "Failed to install packages."
+    exit 1
+fi
 if [ $LOCALE != "en_US" ]; then
     /condinaut -l "$SCRIPT_DIR/$PACKAGE_VARIANT-l10n.list" -c "${SCRIPT_DIR}/minios_build.conf" -m "${SCRIPT_DIR}/condinaut.conf"
+    if [ $? -ne 0 ]; then
+        echo "Failed to install packages."
+        exit 1
+    fi
 fi
 
 rm -f /usr/share/applications/xterm.desktop
diff --git a/linux-live/scripts/10-firefox/install b/linux-live/scripts/10-firefox/install
--- a/linux-live/scripts/10-firefox/install
+++ b/linux-live/scripts/10-firefox/install
@@ -24,6 +24,10 @@ EOF
 fi
 
 /condinaut -l "${SCRIPT_DIR}/packages.list" -c "${SCRIPT_DIR}/minios_build.conf" -m "${SCRIPT_DIR}/condinaut.conf"
+if [ $? -ne 0 ]; then
+    echo "Failed to install packages."
+    exit 1
+fi
 
 # Conditional Desktop environment settings
 if [[ "${DESKTOP_ENVIRONMENT}" == *"xfce"* ]] && [ "${PACKAGE_VARIANT}" != "puzzle" ]; then
