Update 20241123

diff --git a/minios-cmd b/minios-cmd
--- a/minios-cmd
+++ b/minios-cmd
@@ -32,37 +32,64 @@ help() {
     echo -e "${BOLD}$(gettext "Options:")${ENDCOLOR}"
     echo ""
     echo -e "${LIGHTBLUE}$(gettext "Build Options:")${ENDCOLOR}"
-    echo -e "  ${LIGHTGREEN}-b, --build-dir${ENDCOLOR} DIR             $(gettext "Specify the build directory.")"
+    echo -e "  ${LIGHTGREEN}-b, --build-dir${ENDCOLOR} DIR               $(gettext "Specify the build directory.")"
     echo ""
     echo -e "${LIGHTBLUE}$(gettext "System Options:")${ENDCOLOR}"
     echo -e "  ${LIGHTGREEN}-d, --distribution${ENDCOLOR} NAME           $(gettext "Specify the distribution name (e.g., 'bookworm').")"
     echo -e "  ${LIGHTGREEN}-a, --architecture${ENDCOLOR} NAME           $(gettext "Specify the architecture (e.g., 'amd64').")"
     echo -e "  ${LIGHTGREEN}-de, --desktop-environment${ENDCOLOR} NAME   $(gettext "Specify the desktop environment (e.g., 'xfce').")"
-    echo -e "  ${LIGHTGREEN}-pv, --package-variant${ENDCOLOR} NAME        $(gettext "Specify the package variant (e.g., 'standard').")"
+    echo -e "  ${LIGHTGREEN}-pv, --package-variant${ENDCOLOR} NAME       $(gettext "Specify the package variant (e.g., 'standard').")"
     echo -e "  ${LIGHTGREEN}-c, --compression-type${ENDCOLOR} NAME       $(gettext "Specify the compression type (e.g., 'zstd').")"
     echo ""
     echo -e "${LIGHTBLUE}$(gettext "Kernel Options:")${ENDCOLOR}"
-    echo -e "  ${LIGHTGREEN}-kt, --kernel-type${ENDCOLOR} NAME            $(gettext "Specify the kernel type (e.g., 'default').")"
-    echo -e "  ${LIGHTGREEN}-bpo, --kernel-backports${ENDCOLOR} VALUE     $(gettext "Enable or disable kernel backports (true/false).")"
-    echo -e "  ${LIGHTGREEN}-aufs, --kernel-aufs${ENDCOLOR} VALUE         $(gettext "Enable or disable AUFS support in the kernel (true/false).")"
-    echo -e "  ${LIGHTGREEN}-dkms, --kernel-build-dkms${ENDCOLOR} VALUE   $(gettext "Enable or disable DKMS for wireless drivers (true/false).")"
+    echo -e "  ${LIGHTGREEN}-kt, --kernel-type${ENDCOLOR} NAME           $(gettext "Specify the kernel type (e.g., 'default').")"
+    echo -e "  ${LIGHTGREEN}-bpo, --kernel-backports${ENDCOLOR} VALUE    $(gettext "Enable or disable the use of the Linux kernel from backports (true/false). Only available for original Debian kernels")"
+    echo -e "  ${LIGHTGREEN}-aufs, --kernel-aufs${ENDCOLOR} VALUE        $(gettext "Enable or disable AUFS support in the kernel (true/false).")"
+    echo -e "  ${LIGHTGREEN}-dkms, --kernel-build-dkms${ENDCOLOR} VALUE  $(gettext "Enable or disable compilation of additional drivers during kernel installation (true/false).")"
     echo ""
     echo -e "${LIGHTBLUE}$(gettext "Locale and Timezone Options:")${ENDCOLOR}"
-    echo -e "  ${LIGHTGREEN}-l, --locale${ENDCOLOR} NAME                  $(gettext "Specify the system locale (e.g., 'en_US').")"
-    echo -e "  ${LIGHTGREEN}-ml, --multilingual${ENDCOLOR} VALUE          $(gettext "Enable or disable multilingual support (true/false).")"
-    echo -e "  ${LIGHTGREEN}-kl, --keep-locales${ENDCOLOR} VALUE          $(gettext "Keep all available locales (true/false).")"
-    echo -e "  ${LIGHTGREEN}-tz, --timezone${ENDCOLOR} NAME               $(gettext "Specify the timezone (e.g., 'Etc/UTC').")"
+    echo -e "  ${LIGHTGREEN}-l, --locale${ENDCOLOR} NAME                 $(gettext "Specify the system locale (e.g., 'en_US').")"
+    echo -e "  ${LIGHTGREEN}-ml, --multilingual${ENDCOLOR} VALUE         $(gettext "Enable or disable multilingual support (true/false).")"
+    echo -e "  ${LIGHTGREEN}-kl, --keep-locales${ENDCOLOR} VALUE         $(gettext "Keep all available locales (true/false).")"
+    echo -e "  ${LIGHTGREEN}-tz, --timezone${ENDCOLOR} NAME              $(gettext "Specify the timezone (e.g., 'Etc/UTC').")"
+    echo ""
+    echo -e "${BOLD}$(gettext "Default Settings:")${ENDCOLOR}"
+    echo ""
+    echo -e "${LIGHTBLUE}$(gettext "Distribution Settings:")${ENDCOLOR}"
+    echo -e "  ${LIGHTGREEN}DISTRIBUTION=${ENDCOLOR} \"bookworm\""
+    echo -e "  ${LIGHTGREEN}DISTRIBUTION_ARCH=${ENDCOLOR} \"amd64\""
+    echo -e "  ${LIGHTGREEN}DESKTOP_ENVIRONMENT=${ENDCOLOR} \"xfce\""
+    echo -e "  ${LIGHTGREEN}PACKAGE_VARIANT=${ENDCOLOR} \"standard\""
+    echo -e "  ${LIGHTGREEN}COMP_TYPE=${ENDCOLOR} \"zstd\""
+    echo ""
+    echo -e "${LIGHTBLUE}$(gettext "Kernel Settings:")${ENDCOLOR}"
+    echo -e "  ${LIGHTGREEN}KERNEL_TYPE=${ENDCOLOR} \"default\""
+    echo -e "  ${LIGHTGREEN}KERNEL_BPO=${ENDCOLOR} \"false\""
+    echo -e "  ${LIGHTGREEN}KERNEL_AUFS=${ENDCOLOR} \"true\""
+    echo -e "  ${LIGHTGREEN}KERNEL_BUILD_DKMS=${ENDCOLOR} \"true\""
+    echo ""
+    echo -e "${LIGHTBLUE}$(gettext "Locale & Timezone Settings:")${ENDCOLOR}"
+    echo -e "  ${LIGHTGREEN}LOCALE=${ENDCOLOR} \"en_US\""
+    echo -e "  ${LIGHTGREEN}MULTILINGUAL=${ENDCOLOR} \"false\""
+    echo -e "  ${LIGHTGREEN}KEEP_ALL_LOCALES=${ENDCOLOR} \"true\""
+    echo -e "  ${LIGHTGREEN}TIMEZONE=${ENDCOLOR} \"Etc/UTC\""
     echo ""
     echo -e "${BOLD}$(gettext "Examples:")${ENDCOLOR}"
     echo ""
     echo -e "  $(gettext "1. Create a system image with the 'bookworm' distribution, 'amd64' architecture, and 'xfce' desktop environment:")"
     echo -e "     $(basename $0) --distribution bookworm --architecture amd64 --desktop-environment xfce"
     echo ""
-    echo -e "  $(gettext "2. Create a system image with kernel backports and AUFS support enabled:")"
-    echo -e "     $(basename $0) --kernel-backports true --kernel-aufs true"
+    echo -e "  $(gettext "2. Create a system image with 'buster' distribution, 'i386' architecture, and 'xfce' desktop environment:")"
+    echo -e "     $(basename $0) --distribution buster --architecture i386 --desktop-environment xfce"
     echo ""
-    echo -e "  $(gettext "3. Specify a custom output directory and enable verbose output:")"
-    echo -e "     $(basename $0) --output /path/to/output --verbose"
+    echo -e "  $(gettext "3. Create a system image with kernel backports:")"
+    echo -e "     $(basename $0) --kernel-backports true --kernel-aufs false"
+    echo ""
+    echo -e "  $(gettext "4. Create a system image with the 'jammy' distribution and 'standard' package variant:")"
+    echo -e "     $(basename $0) --distribution jammy --package-variant standard"
+    echo ""
+    echo -e "  $(gettext "5. Create a system image with 'trixie' distribution, 'amd64' architecture, and 'xfce' desktop environment with multilingual support enabled:")"
+    echo -e "     $(basename $0) --distribution trixie --architecture amd64 --desktop-environment xfce --multilingual true"
     echo ""
     echo -e "  $(basename $0) $(gettext "has many more options available. Please refer to the above options list for more details.")"
     exit 0
@@ -154,10 +181,10 @@ toggle_shell_options e
 
 : "${BUILD_SCRIPTS_DIR:="linux-live"}"
 : "${BUILD_DIR:="${PWD}/build"}"
-: "${DISTRIBUTION:="bookworm"}"
-: "${DISTRIBUTION_ARCH:="amd64"}"
-: "${DESKTOP_ENVIRONMENT:="xfce"}"
-: "${PACKAGE_VARIANT:="standard"}"
+: "${DISTRIBUTION:=}"
+: "${DISTRIBUTION_ARCH:=}"
+: "${DESKTOP_ENVIRONMENT:=}"
+: "${PACKAGE_VARIANT:=}"
 : "${COMP_TYPE:="zstd"}"
 : "${KERNEL_TYPE:="default"}"
 : "${KERNEL_BPO:=false}"
@@ -167,6 +194,13 @@ toggle_shell_options e
 : "${MULTILINGUAL:=false}"
 : "${KEEP_ALL_LOCALES:=true}"
 : "${TIMEZONE:="Etc/UTC"}"
+
+# Check if mandatory parameters are set
+if [[ -z "$DISTRIBUTION" || -z "$DISTRIBUTION_ARCH" || -z "$DESKTOP_ENVIRONMENT" || -z "$PACKAGE_VARIANT" ]]; then
+    error "The following options are required: -d/--distribution, -a/--architecture, -de/--desktop-environment, -pv/--package-variant"
+    brief_help
+    exit 1
+fi
 
 # ----[ MAIN ]----
 
