Add error handling for package installation failures across multiple scripts

diff --git a/linux-live/scripts/01-kernel/install b/linux-live/scripts/01-kernel/install
--- a/linux-live/scripts/01-kernel/install
+++ b/linux-live/scripts/01-kernel/install
@@ -71,6 +71,10 @@ if [ "${KERNEL_TYPE}" != "none" ]; then
 
     # Call the external condinaut script.
     /condinaut -l "${TMP_PKGLIST}" -c "/minios_build.conf" -m "/condinaut.conf"
+    if [ $? -ne 0 ]; then
+        echo "Failed to install packages."
+        exit 1
+    fi
 
     # If installing from the repository, hold the kernel package.
     if [ ! -d "/rootcopy-install" ] || [ -z "${DEB}" ]; then
diff --git a/linux-live/scripts/02-firmware/install b/linux-live/scripts/02-firmware/install
--- a/linux-live/scripts/02-firmware/install
+++ b/linux-live/scripts/02-firmware/install
@@ -13,3 +13,7 @@ echo "firmware-ipw2x00 firmware-ipw2x00/license/accepted boolean true" | debconf
 echo "b43-fwcutter b43-fwcutter/install-unconditional boolean true" | debconf-set-selections
 
 /condinaut -l "${SCRIPT_DIR}/packages.list" -c "${SCRIPT_DIR}/minios_build.conf" -m "${SCRIPT_DIR}/condinaut.conf"
+if [ $? -ne 0 ]; then
+    error "Failed to install packages."
+    exit 1
+fi
diff --git a/linux-live/scripts/03-gui-base/install b/linux-live/scripts/03-gui-base/install
--- a/linux-live/scripts/03-gui-base/install
+++ b/linux-live/scripts/03-gui-base/install
@@ -12,6 +12,10 @@ console_colors
 SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
 
 /condinaut -l "${SCRIPT_DIR}/packages.list" -c "${SCRIPT_DIR}/minios_build.conf" -m "${SCRIPT_DIR}/condinaut.conf"
+if [ $? -ne 0 ]; then
+    echo "Failed to install packages."
+    exit 1
+fi
 
 if pkg_is_installed "xrdp" >/dev/null 2>&1; then
     adduser xrdp ssl-cert
diff --git a/linux-live/scripts/04-flux-desktop/install b/linux-live/scripts/04-flux-desktop/install
--- a/linux-live/scripts/04-flux-desktop/install
+++ b/linux-live/scripts/04-flux-desktop/install
@@ -6,8 +6,10 @@
 SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
 
 /condinaut -l "${SCRIPT_DIR}/packages.list" -c "${SCRIPT_DIR}/minios_build.conf" -m "${SCRIPT_DIR}/condinaut.conf"
-
-(cd /rootcopy-install && cp --parents -afr * /)
+if [ $? -ne 0 ]; then
+    echo "Failed to install packages."
+    exit 1
+fi
 
 rm -f /usr/share/applications/chromium-flux.desktop
 rm -f /usr/share/applications/compton.desktop
