Update 20230710

diff --git a/linux-live/scripts/10-palemoon/install b/linux-live/scripts/10-palemoon/install
--- a/linux-live/scripts/10-palemoon/install
+++ b/linux-live/scripts/10-palemoon/install
@@ -1,7 +1,12 @@
 #!/bin/bash
 
-#apt-get $INSTALL_OPTIONS update >>$OUTPUT 2>&1 &&
-#    apt-get $INSTALL_OPTIONS install gnupg >>$OUTPUT 2>&1
+set -e          # exit on error
+set -o pipefail # exit on pipeline error
+set -u          # treat unset variable as error
+
+SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
+
+. /minioslib || exit 1
 
 if [ $DISTRIBUTION_TYPE = "debian" ]; then
     echo 'deb http://download.opensuse.org/repositories/home:/stevenpusser/Debian_10/ /' | tee /etc/apt/sources.list.d/home:stevenpusser.list
@@ -12,8 +17,8 @@ elif [ $DISTRIBUTION_TYPE = "ubuntu" ]; then
 fi
 
 # install packages
-apt-get $INSTALL_OPTIONS update >>$OUTPUT 2>&1 &&
-    apt-get $INSTALL_OPTIONS install palemoon >>$OUTPUT 2>&1
+pkg update
+pkg install palemoon
 
 if [[ $DESKTOP_ENVIRONMENT == *"xfce"* ]] && [ $PACKAGE_VARIANT != "puzzle" ]; then
     if [ ! -d /etc/skel/.config/xfce4 ]; then
