Update 20230605

diff --git a/linux-live/kernelconfig b/linux-live/kernelconfig
--- a/linux-live/kernelconfig
+++ b/linux-live/kernelconfig
@@ -1,41 +1,60 @@
 #!/bin/bash
 
-##########################################
-
-if [ $DISTRIBUTION_ARCH = "amd64" ]; then
+case $DISTRIBUTION_ARCH in
+"amd64")
     KERNEL_ARCH="amd64"
-elif [ $DISTRIBUTION_ARCH = "i386-pae" ]; then
+    ;;
+"i386-pae")
     KERNEL_ARCH="686-pae"
-elif [ $DISTRIBUTION_ARCH = "i386" ]; then
+    ;;
+"i386")
     KERNEL_ARCH="686"
-elif [ $DISTRIBUTION_ARCH = "arm64" ]; then
+    ;;
+"arm64")
     KERNEL_ARCH="arm64"
-fi
+    ;;
+esac
 
 if [ $PACKAGE_VARIANT = "pve" ]; then
-    KERNEL_TYPE="pve"
-elif [ $PACKAGE_VARIANT = "pve" ] && [ $DISTRIBUTION_ARCH != "amd64" ]; then
-    echo "You can't build PVE with i386"
-    exit 0
+    if [ $DISTRIBUTION_ARCH = "amd64" ]; then
+        KERNEL_TYPE="pve"
+    else
+        echo "You can't build PVE with i386"
+        exit 1
+    fi
 fi
 if [ $KERNEL_TYPE = "pve" ] && [ $DISTRIBUTION_ARCH != "amd64" ]; then
     KERNEL_TYPE = "default"
 fi
 
-if [ $KERNEL_AUFS = "true" ] && ! { [ $DISTRIBUTION = "stretch" ] || [ $DISTRIBUTION = "buster" ] || [ $DISTRIBUTION = "orel" ] || [ $DISTRIBUTION = "bookworm" ]; }; then
-    if [ $KERNEL_BPO = "true" ]; then
-        KERNEL_VERSION="6.0"
-    else
-        KERNEL_VERSION="5.10"
-    fi
-    if [ $KERNEL_TYPE = "default" ]; then
+if [ $KERNEL_AUFS = "true" ]; then
+    case $DISTRIBUTION in
+    "bookworm" | "sid" | "kali-rolling")
+        KERNEL_VERSION="6.1"
         KERNEL=$(apt-cache depends linux-image-$KERNEL_VERSION-mos-$KERNEL_ARCH | grep 'Depends' | sed 's/  Depends: //g' | sed 's/linux-image-//')
-    else
-        KERNEL=$(apt-cache depends linux-image-$KERNEL_VERSION-mos-$KERNEL_TYPE-$KERNEL_ARCH | grep 'Depends' | sed 's/  Depends: //g' | sed 's/linux-image-//')
-    fi
-elif [ $KERNEL_AUFS = "true" ] && [ $DISTRIBUTION = "bookworm" ]; then
-    KERNEL_VERSION="6.1"
-    KERNEL=$(apt-cache depends linux-image-$KERNEL_VERSION-mos-$KERNEL_ARCH | grep 'Depends' | sed 's/  Depends: //g' | sed 's/linux-image-//')
+        ;;
+    "bullseye" | "bionic" | "focal" | "jammy")
+        if [ $KERNEL_BPO = "true" ]; then
+            KERNEL_VERSION="6.1"
+        else
+            KERNEL_VERSION="5.10"
+        fi
+        if [ $KERNEL_TYPE = "default" ]; then
+            KERNEL=$(apt-cache depends linux-image-$KERNEL_VERSION-mos-$KERNEL_ARCH | grep 'Depends' | sed 's/  Depends: //g' | sed 's/linux-image-//')
+        else
+            KERNEL=$(apt-cache depends linux-image-$KERNEL_VERSION-mos-$KERNEL_TYPE-$KERNEL_ARCH | grep 'Depends' | sed 's/  Depends: //g' | sed 's/linux-image-//')
+        fi
+        ;;
+    "stretch" | "buster" | "orel")
+        if [ -f /usr/bin/dpkg-query ] 2>/dev/null; then
+            KERNEL=$(dpkg-query -W -f='${binary:Package}\n' linux-image-* 2>/dev/null | head -n 1 | sed 's/linux-image-//')
+            KERNEL_VERSION=""
+        else
+            KERNEL=$(uname -r)
+            KERNEL_VERSION=""
+        fi
+        ;;
+    esac
 elif [ $KERNEL_TYPE = "none" ]; then
     KERNEL=""
 elif [ -f /usr/bin/dpkg-query ] 2>/dev/null; then
@@ -45,6 +64,7 @@ else
     KERNEL=$(uname -r)
     KERNEL_VERSION=""
 fi
+
 if echo $KERNEL | grep -q 'pve'; then
     KERNEL=${KERNEL::-6}
 fi
diff --git a/linux-live/scripts/00-minios/rootcopy-install/usr/bin/minios-resolution b/linux-live/scripts/00-minios/rootcopy-install/usr/bin/minios-resolution
--- a/linux-live/scripts/00-minios/rootcopy-install/usr/bin/minios-resolution
+++ b/linux-live/scripts/00-minios/rootcopy-install/usr/bin/minios-resolution
@@ -1,47 +1,59 @@
 #!/bin/bash
 
-# Check if the script is passed with all parameters
-if [[ "$#" -ne 1 ]]; then
-    echo "Usage: $0 <WIDTH>x<HEIGHT>"
-    echo "Example: $0 1920x1080"
-    exit 1
-fi
+# Show the form and save the values to variables
 
-export DISPLAY=:0
-XAUTHORITY_FILE="/home/$USER/.Xauthority"
-# Check if the XAUTHORITY_FILE exists
-if [ ! -f "$XAUTHORITY_FILE" ]; then
-    # Use the root user's .Xauthority file
-    XAUTHORITY_FILE="/$USER/.Xauthority"
-fi
-export XAUTHORITY="$XAUTHORITY_FILE"
+RESOLUTION=$(yad --form --title="Enter Resolution" \
+    --field="Width:":NUM \
+    --field="Height:":NUM \
+    --width=300 \
+    --height=150 \
+    --margin=30 \
+    --button="Submit":0 \
+    --button="Cancel":1 \
+ )
 
-# Get resolution parameters from the argument
-RESOLUTION="$1"
-WIDTH=$(echo "$RESOLUTION" | cut -d'x' -f1)
-HEIGHT=$(echo "$RESOLUTION" | cut -d'x' -f2)
-REFRESH_RATE=60
 
-# Get the first display name from the xrandr output
-DISPLAY_NAME=$(xrandr | grep " connected " | awk '{ print $1 }' | head -n 1)
+# Check if the user clicked "Submit"
+if [ $? -eq 0 ]; then
+    # Extract the values from the form output
+    WIDTH=$(echo $RESOLUTION | awk -F '|' '{print $1}')
+    HEIGHT=$(echo $RESOLUTION | awk -F '|' '{print $2}')
 
-# Use the gtf command to calculate the resolution model
-MODEL=$(gtf $WIDTH $HEIGHT $REFRESH_RATE | grep Modeline | cut -d' ' -f 4- | sed 's/["'\'']//g')
-
-# Check if the resolution model calculation is successful
-if [[ -n "$MODEL" ]]; then
-    # Check if the new resolution model is already added to the available modes list
-    if ! (xrandr | grep -q "${WIDTH}x${HEIGHT}_${REFRESH_RATE}.00"); then
-        # Add the new resolution model to the available modes list
-        xrandr --newmode $MODEL
-
-        # Add the new resolution model to the available modes list for the given screen
-        xrandr --addmode $DISPLAY_NAME "${WIDTH}x${HEIGHT}_${REFRESH_RATE}.00"
+    export DISPLAY=:0
+    XAUTHORITY_FILE="/home/$USER/.Xauthority"
+    # Check if the XAUTHORITY_FILE exists
+    if [ ! -f "$XAUTHORITY_FILE" ]; then
+        # Use the root user's .Xauthority file
+        XAUTHORITY_FILE="/$USER/.Xauthority"
     fi
+    export XAUTHORITY="$XAUTHORITY_FILE"
 
-    # Set the new screen resolution
-    xrandr --output $DISPLAY_NAME --mode "${WIDTH}x${HEIGHT}_${REFRESH_RATE}.00"
+    REFRESH_RATE=60
 
+    # Get the first display name from the xrandr output
+    DISPLAY_NAME=$(xrandr | grep " connected " | awk '{ print $1 }' | head -n 1)
+
+    # Use the gtf command to calculate the resolution model
+    MODEL=$(gtf $WIDTH $HEIGHT $REFRESH_RATE | grep Modeline | cut -d' ' -f 4- | sed 's/["'\'']//g')
+
+    # Check if the resolution model calculation is successful
+    if [[ -n "$MODEL" ]]; then
+        # Check if the new resolution model is already added to the available modes list
+        if ! (xrandr | grep -q "${WIDTH}x${HEIGHT}_${REFRESH_RATE}.00"); then
+            # Add the new resolution model to the available modes list
+            xrandr --newmode $MODEL
+
+            # Add the new resolution model to the available modes list for the given screen
+            xrandr --addmode $DISPLAY_NAME "${WIDTH}x${HEIGHT}_${REFRESH_RATE}.00"
+        fi
+
+        # Set the new screen resolution
+        xrandr --output $DISPLAY_NAME --mode "${WIDTH}x${HEIGHT}_${REFRESH_RATE}.00"
+
+    else
+        echo "Failed to calculate the resolution model"
+    fi
 else
-    echo "Failed to calculate the resolution model"
+    # User clicked "Cancel"
+    echo "Form closed without submitting"
 fi
