Update 20230827

diff --git a/linux-live/initramfs/livekit-mos/livekitlib b/linux-live/initramfs/livekit-mos/livekitlib
--- a/linux-live/initramfs/livekit-mos/livekitlib
+++ b/linux-live/initramfs/livekit-mos/livekitlib
@@ -514,6 +514,18 @@ find_data_try() {
    blkid /dev/* | sort | cut -d: -f 1 | grep -E -v "/loop|/ram|/zram" | while read DEVICE; do
       #blkid | sort | cut -d: -f 1 | grep -E -v "/loop|/ram|/zram" | while read DEVICE; do
       FROM="$2"
+
+      # supported syntax is even like from=/dev/sr0/livekitname. It is not so much
+      # optiomal to put the following block of code here inside the while loop,
+      # but there is no harm so lets modify DEVICE and FROM to make it work
+      if echo "$FROM" | grep -q '^/dev/'; then
+         DEVICE="$(echo "$FROM" | cut -d '/' -f 1-3)"
+         FROM="$(echo "$FROM" | cut -d '/' -f 4-)"
+         if [ "$FROM" = "" ]; then
+            FROM="$LIVEKITNAME"
+         fi
+      fi
+
       FS="$(device_bestfs "$DEVICE")"
       OPTIONS="$(fs_options $FS)"
       MOUNT="$(mount_command $FS)"
@@ -530,7 +542,16 @@ find_data_try() {
       # search for bundles in the mounted directory
       if [ "$(find "$1/$FROM" -maxdepth 1 -name "*.$BEXT" 2>/dev/null)" != "" ]; then
          # we found at least one bundle/module here
+         echo "$FROM" >/var/log/from.log
          echo "$1/$FROM" | tr -s "/" | sed -r "s:/[^/]+/[.][.]/:/:g"
+         return
+      fi
+
+      # search for bundles in modules directory
+      if [ "$(find "$1/$FROM/modules" -maxdepth 1 -name "*.$BEXT" 2>/dev/null)" != "" ]; then
+         # we found at least one bundle/module here
+         echo "$1/$FROM" | tr -s "/" | sed -r "s:/[^/]+/[.][.]/:/:g"
+         echo "$FROM" >/var/log/from.log
          return
       fi
 
@@ -592,6 +613,85 @@ check_data_found() {
    fi
 }
 
+
+# Get a human readable format of time elapsed since given datetime
+# $1 = date time
+#
+date_diff_since_now() {
+   now=$(date '+%s')
+   timestamp=$(date --date "$1" '+%s')
+   sec=$(($now - $timestamp))
+   mins=$(($sec / 60))
+   hours=$(($sec / 3600))
+   days=$(($sec / 86400))
+
+   if [ "$days" -gt 0 ]; then
+      echo "$days days" | sed -r "s/^1 days/1 day/"
+   elif [ "$hours" -gt 0 ]; then
+      echo "$hours hours" | sed -r "s/^1 hours/1 hour/"
+   elif [ "$mins" -gt 0 ]; then
+      echo "$mins minutes" | sed -r "s/^1 minutes/1 minute/"
+   else
+      echo "$sec seconds" | sed -r "s/^1 seconds/1 second/"
+   fi
+}
+
+# Restore persistent changes from previous session.
+# Store persistent changes to a directory and keep the directory in a session file,
+# so we know which session was active last time so we can resume it next time
+# $1 = changes directory
+# $2 = currently requested perch directory (e.g. '3')
+#
+restore_perch_session() {
+   debug_log "restore_perch_session" "$*"
+
+   local CHANDIR SESSDIR FILE LAST LASTMOD LASTSESSION NEW DIR USAGE LAST DAYS
+
+   CHANDIR="$1"
+   SESSDIR="$2"
+   LAST=last_session.txt
+
+   LASTSESSION=$(cat "$CHANDIR/$LAST" 2>/dev/null)
+
+   # ask for session, print msgs to stderr so it is visible
+   if [ "$LASTSESSION" != "" -a "$SESSDIR" = "ask" ]; then
+      echo "" >&2
+      echo "Choose session to resume from the list:" >&2
+      echo "---------------------------------------" >&2
+
+      ls -1 $CHANDIR | grep -E "^[0-9]+" | while read DIR; do
+         USAGE=$(du -s -h "$CHANDIR/$DIR" 2>/dev/null | sed -r "s/[[:space:]].*//")
+         LASTMOD="$(date -r "$CHANDIR/$DIR" "+%Y-%m-%d %H:%M:%S")"
+         DAYS=$(date_diff_since_now "$LASTMOD")
+         echo "$LASTMOD Session #$DIR - last access $DAYS ago - using $USAGE" | sed -r "s/(.)\$/ \\1B/"
+      done | sort -r | cut -d " " -f 3- >&2
+
+      echo "---------------------------------------" >&2
+      echo -ne "Type session number to resume and press Enter ($LASTSESSION): " >&2
+      read SESSDIR
+
+      SESSDIR=$(echo "$SESSDIR" | sed -r "s/[^0-9]//g")
+   fi
+
+   # restore name for previous session if empty
+   if [ "$SESSDIR" = "" -o "$SESSDIR" = "resume" ]; then
+      SESSDIR="$LASTSESSION"
+   fi
+
+   # if last is empty or new/nonexistent is requested, create new
+   if [ "$SESSDIR" = "" -o "$SESSDIR" = "new" -o ! -d "$CHANDIR/$SESSDIR" ]; then
+      NEW="$(ls -1 $CHANDIR | egrep '^[0-9]' | sed -r 's/[^0-9].*//' | sort | tail -n 1)"
+      NEW=$(($NEW + 1))
+      mkdir -p "$CHANDIR/$NEW"
+      SESSDIR="$NEW"
+   fi
+
+   # remember current, update timestamp
+   echo "$SESSDIR" >"$CHANDIR/$LAST"
+   touch "$CHANDIR/$SESSDIR"
+   echo "$SESSDIR"
+}
+
 # Activate persistent changes
 # $1 = data directory
 # $2 = target changes directory
@@ -599,7 +699,7 @@ check_data_found() {
 persistent_changes() {
    debug_log "persistent_changes" "$*"
 
-   local CHANGES T1 T2 EXISTS DEVICE PERCHFILE PERCHSIZE SPLITSIZE SUFFIX
+   local CHANGES T1 T2 EXISTS DEVICE PERCHDIR PERCHSIZE PERCHFILE SUFFIX
 
    CHANGES="$1/$(basename "$2")"
    DEVICE="$(df $1 | tail -n 1 | cut -d " " -f 1)"
@@ -610,6 +710,7 @@ persistent_changes() {
    mkdir -p "$2"
 
    # If persistent changes are not requested, end here
+   # so memory will be used to save chanves temporarily
    if grep -vq perch /proc/cmdline; then
       return
    fi
@@ -623,58 +724,56 @@ persistent_changes() {
       return
    fi
 
-   PERCHSIZE=$(cmdline_value perchsize)
-   PERCHFILE=$(cmdline_value perchfile)
+   PERCHDIR=$(cmdline_value perchdir)
+   PERCHDIR=$(restore_perch_session "$CHANGES" "$PERCHDIR")
 
-   # if neither perchfile nor perchsize is specified, try to use native fs
-   if [ "$PERCHFILE" = "" -a "$PERCHSIZE" = "" ]; then
-      echo_green_star
-      echo "Testing persistent changes for posix compatibility"
-      touch "$T1" && ln -sf "$T1" "$T2" 2>/dev/null &&
-         chmod +x "$T1" 2>/dev/null && test -x "$T1" &&
-         chmod -x "$T1" 2>/dev/null && test ! -x "$T1" &&
-         rm "$T1" "$T2" 2>/dev/null
+   # try to use native fs if posix-compatible
+   echo_green_star
+   echo "Testing persistent changes for posix compatibility"
+   touch "$T1" && ln -sf "$T1" "$T2" 2>/dev/null &&
+      chmod +x "$T1" 2>/dev/null && test -x "$T1" &&
+      chmod -x "$T1" 2>/dev/null && test ! -x "$T1" &&
+      rm "$T1" "$T2" 2>/dev/null
 
-      if [ $? -eq 0 ]; then
-         if device_bestfs $DEVICE | grep -v ntfs >/dev/null; then
-            echo "* Activating native persistent changes"
-            mount --bind "$CHANGES" "$2"
-            return
-         fi
+   if [ $? -eq 0 ]; then
+      if device_bestfs $DEVICE | grep -v ntfs >/dev/null; then
+         echo "* Activating native persistent changes for session #$PERCHDIR"
+         mount --bind "$CHANGES/$PERCHDIR" "$2"
+         return
       fi
+   else
+      # if test failed at any point, we may have temp files left behind
+      rm "$T1" "$T2" 2>/dev/null
    fi
 
-   # If we are here, native fs was not supported or user requested perchfile anyway
+   # If we are here, native fs was not supported or user requested perchsize anyway
 
-   SPLITSIZE=4000
-
-   if [ "$PERCHFILE" = "" ]; then
-      PERCHFILE="changes.dat"
-   fi
+   PERCHSIZE=$(cmdline_value perchsize)
 
    if [ "$PERCHSIZE" = "" ]; then
       PERCHSIZE=16000
    fi
 
-   # restore or use new
+   PERCHFILE="$PERCHDIR/changes.dat"
+
+   # resume or use new
    if [ -e "$CHANGES/$PERCHFILE" ]; then
-      echo "* Restoring persistent changes from $PERCHFILE"
+      echo "* Resuming persistent changes for session #$PERCHDIR"
       EXISTS="true"
    else
-      echo "* Creating new persistent changes in $PERCHFILE"
+      echo "* Creating new persistent changes for session #$PERCHDIR"
       EXISTS=""
    fi
 
-   @mount.dynfilefs -f "$CHANGES/$PERCHFILE" -s $PERCHSIZE -m "$2" -p $SPLITSIZE
+   # mount it, splitsize of 4000MB is hardcoded, it must be the same all the time anyway
+   @mount.dynfilefs -f "$CHANGES/$PERCHFILE" -s $PERCHSIZE -m "$2" -p 4000
    if [ "$EXISTS" ]; then
-      resize2fs "$2/virtual.dat" >/dev/null 2>&1
+      resize2fs -f "$2/virtual.dat" >/dev/null 2>&1
    else
-      mke2fs "$2/virtual.dat" >/dev/null 2>&1
+      mke2fs -F "$2/virtual.dat" >/dev/null 2>&1
    fi
    mount -o loop "$2/virtual.dat" "$2"
 
-   # if test failed at any point, we may have temp files left behind
-   rm "$T1" "$T2" 2>/dev/null
    rmdir "$2/lost+found" 2>/dev/null
 }
 
@@ -800,7 +899,7 @@ union_append_bundles() {
       echo_green_star
       echo "Adding bundles to union"
       find "$1" -mindepth 1 -maxdepth 1 | sortmod | while read BUNDLE; do
-         mount -o remount,add:1:"$BUNDLE" aufs "$2"
+         mount -o remount,add:1:"$BUNDLE=rr+wh" aufs "$2"
       done
    fi
 }
